#!/usr/bin/env node
/**
 * Packages the shared extension source in src/ into per-browser bundles:
 *   dist/chrome/   (Manifest V3, background.service_worker)
 *   dist/firefox/  (Manifest V3, background.scripts — Firefox doesn't run
 *                   service workers as extension background contexts yet;
 *                   see README.md for the source on that.)
 *
 * No bundler, no npm dependencies — this is a copy + JSON-merge script, in
 * keeping with the rest of this repo's no-build-step philosophy. The one
 * exception to "no build step" is this file itself, which exists solely to
 * resolve the Chrome/Firefox manifest divergence (see README.md, "Why a
 * build script").
 *
 * IMPORTANT: dictionary.json is never hand-copied or forked. This script
 * copies it fresh from webapp/data/dictionary.json (generated by
 * scripts/parse.py from the source .docx) every time it runs, so the
 * extension and the PWA always read the same data. Re-run this after
 * regenerating that file.
 *
 * Usage: node build.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const SRC = path.join(ROOT, "src");
const DIST = path.join(ROOT, "dist");
const DICTIONARY_SOURCE = path.join(ROOT, "..", "webapp", "data", "dictionary.json");

const TARGETS = ["chrome", "firefox"];

// Files/dirs copied as-is into every target bundle. Everything here is
// browser-agnostic; only manifest.json and data/dictionary.json are
// generated per target below.
//
// NOTE (2026-08-06): src/view.html, src/view.css, and src/view.js still
// exist on disk but are deliberately NOT listed here anymore — "full view"
// and context-menu lookups now open the live PWA (shared/config.js) instead
// of a bundled page, per README.md. Those three files couldn't be deleted
// from this environment (the connected folder doesn't allow file deletion
// here), so they're orphaned source rather than gone; safe to delete
// manually next time you're in Finder/VS Code. Re-add them here if that
// decision ever gets reversed.
const SHARED_ENTRIES = [
  "background.js",
  "popup.html",
  "popup.css",
  "popup.js",
  "shared",
  "icons",
];

function rmrf(dir) {
  // Best-effort clean: some sandboxed/synced filesystems (e.g. this repo's
  // connected-folder environment during development) disallow unlinking
  // files entirely, which throws EPERM here. When that happens we skip the
  // clean step and fall through to copyRecursive() overwriting files in
  // place — new/changed files still land correctly, but files removed from
  // SHARED_ENTRIES won't be swept out of an existing dist/. Delete dist/
  // manually before packaging a release zip if that matters; on a normal
  // local machine this rmSync just works and dist/ is always fully clean.
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch (err) {
    if (err.code !== "EPERM") throw err;
    console.warn(`  (couldn't clean ${path.relative(ROOT, dir)} — filesystem doesn't allow delete here; overwriting in place instead)`);
  }
}

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
      copyRecursive(path.join(src, entry), path.join(dest, entry));
    }
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

function mergeManifest(target) {
  const base = JSON.parse(fs.readFileSync(path.join(SRC, "manifest.base.json"), "utf8"));
  const overridePath = path.join(SRC, `manifest.${target}.json`);
  const override = fs.existsSync(overridePath)
    ? JSON.parse(fs.readFileSync(overridePath, "utf8"))
    : {};
  return { ...base, ...override };
}

function buildTarget(target) {
  const outDir = path.join(DIST, target);
  rmrf(outDir);
  fs.mkdirSync(outDir, { recursive: true });

  for (const entry of SHARED_ENTRIES) {
    const srcPath = path.join(SRC, entry);
    if (!fs.existsSync(srcPath)) {
      throw new Error(`Missing expected source entry: src/${entry}`);
    }
    copyRecursive(srcPath, path.join(outDir, entry));
  }

  const manifest = mergeManifest(target);
  fs.writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

  if (!fs.existsSync(DICTIONARY_SOURCE)) {
    throw new Error(
      `Couldn't find ${DICTIONARY_SOURCE}. Run webapp/scripts/parse.py first, or check the path.`
    );
  }
  copyRecursive(DICTIONARY_SOURCE, path.join(outDir, "data", "dictionary.json"));

  console.log(`built dist/${target}/`);
}

for (const target of TARGETS) {
  buildTarget(target);
}

console.log("\nLoad unpacked:");
console.log("  Chrome  → chrome://extensions → Load unpacked → dist/chrome");
console.log("  Firefox → about:debugging#/runtime/this-firefox → Load Temporary Add-on → dist/firefox/manifest.json");
